"""users table

Revision ID: 2db68a70561a
Revises: 76b2ace92d7b
Create Date: 2019-05-07 01:30:25.685716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db68a70561a'
down_revision = '76b2ace92d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'category_id')
    # ### end Alembic commands ###
