"""posts table

Revision ID: 307b6f2a294d
Revises: 2db68a70561a
Create Date: 2019-05-07 01:31:04.604509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307b6f2a294d'
down_revision = '2db68a70561a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('is_appear', sa.Boolean(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_article_id'), 'posts', ['article_id'], unique=False)
    op.create_index(op.f('ix_posts_reply_id'), 'posts', ['reply_id'], unique=False)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_user_to_id'), 'posts', ['user_to_id'], unique=False)
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_index(op.f('ix_posts_user_to_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_reply_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_article_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
