"""users table

Revision ID: de6941f38f3d
Revises: 2b0aab073d30
Create Date: 2019-05-07 12:38:07.191315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6941f38f3d'
down_revision = '2b0aab073d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_to_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
